### ISSUE TITLE
GPU environment

### ISSUE THREAD

**Issue by z050209** [Sirui-Xu/InterDiff#12]
Dear authors, may I know which GPU environment would be sufficient to train this model, if using GRAB or ARCTIC dataset?

thanks.

**Comment by Sirui-Xu** [comment]
Hello @z050209 ,

I believe our method can be adjusted to suit various GPUs. You have the flexibility to fine-tune several hyperparameters for this adaptation. First,  the [number of points used to represent the geometry of each object](https://github.com/Sirui-Xu/InterDiff/blob/main/interdiff/data/prepare_behave.py#L130) Second, the [batch size](https://github.com/Sirui-Xu/InterDiff/blob/main/interdiff/train_correction_smpl.py#L328) employed for model training. If you encounter VRAM constraints, consider reducing these parameters, and you can identify the optimal parameters for running our pipeline.

Best

**Comment by z050209** [comment]
Thanks, I will try that. 👍
