### ISSUE TITLE
module is not found

### ISSUE THREAD

**Issue by zhihou7** [Sirui-Xu/InterDiff#13]
File "/mnt/petrelfs/houzhi/Code/InterDiff/interdiff/eval_skeleton.py", line 10, in <module>
    from train_correction_skeleton import LitObjInteraction as LitObj
  File "/mnt/petrelfs/houzhi/Code/InterDiff/interdiff/train_correction_skeleton.py", line 15, in <module>
    from dataset.dataset import get_datasets
ModuleNotFoundError: No module named 'dataset.dataset'

Meanwhile, what's your viz version.

Looking forward to your reply.

Best,

**Comment by Sirui-Xu** [comment]
Hi,

Oh I think it should be "from data.dataset_skeleton import get_datasets" and "from render.viz_helper import visualize_skeleton",  viz should not be required.

**Comment by zhihou7** [comment]
Thanks for your quick reply. It seems like this repo contains a lot crashed code. 

May I ask did you provide the skeleton-based pretrained models?

Best,

**Comment by Sirui-Xu** [comment]
We did the SMPL and skeleton part separately, so the problem may be in linking the skeleton section to the module. The other parts should be clean. Please feel free to let us know if you find any other issues!

I can send you a separate clean version of the skeleton prediction if you needed, and I will ask my collaborators to provide the pretrained models for the skeleton dataset.

Thanks

**Comment by Sirui-Xu** [comment]
Hi,

the pretrained models are updated here: https://github.com/Sirui-Xu/InterDiff/tree/main/interdiff/checkpoints.

Best

**Comment by zhihou7** [comment]
> We did the SMPL and skeleton part separately, so the problem may be in linking the skeleton section to the module. The other parts should be clean. Please feel free to let us know if you find any other issues!
> 
> I can send you a separate clean version of the skeleton prediction if you needed, and I will ask my collaborators to provide the pretrained models for the skeleton dataset.
> 
> Thanks

Thanks for your help. That's great!

**Comment by zhihou7** [comment]
> Hi,
> 
> the pretrained models are updated here: https://github.com/Sirui-Xu/InterDiff/tree/main/interdiff/checkpoints.
> 
> Best

Thanks. I can run the code successfully.
