### ISSUE TITLE
denormalize is missing in eval_long

### ISSUE THREAD

**Issue by Kairobo** [Sirui-Xu/InterDiff#14]

**Comment by kleinzcy** [comment]
Same issue.

When you have time to open-source the evaluation of long-term generation?

**Comment by Sirui-Xu** [comment]
Hello,

Here’s the code for denormalizing and evaluation: [link to code](https://drive.google.com/file/d/1xow6GDCC7tJ8kL7W9E5KmgCJ03jA82Zk/view?usp=sharing). It’s not fully organized yet but should produce the same results as reported in the paper.

Will find a time to complete the wrap-up for this part and integrate it into the current codebase.

Best

**Comment by kleinzcy** [comment]
Thanks for your code.  The provided evaluation code contains the denormalize function. But the evaluation is still failed as it missing "correct" function (Line 314 in eval_smpl_long.py).

**Comment by kleinzcy** [comment]
Another question. It takes 10 minutes for 1 epoch on the TITAN RTX. Is it normal? And it occures oserror when num_workers > 0. How do you fix such error?

**Comment by Sirui-Xu** [comment]
The ‘correct’ function should be ‘smooth’ as defined in the [short-term evaluation code](https://github.com/Sirui-Xu/InterDiff/blob/main/interdiff/eval_smpl_short.py#L217), sorry for the confusion

I don’t recall encountering similar cases before in a Linux environment with A40 or TITAN X. The network and dataset are lightweight and should train very quickly.

**Comment by kleinzcy** [comment]
Thanks for your help. However, the evaluation still failed as the get_batch function is not right. The repeat dimension is not right. I have tried, but not solved.

**Comment by Sirui-Xu** [comment]
Hello,

Could you please check if a similar issue would happen when you set batch_size = 1?

**Comment by kleinzcy** [comment]
![image](https://github.com/user-attachments/assets/d9f8dfef-130a-4305-93a1-5f793688862a)

Note that I use the get_batch function provided in eval_smpl_long.

When setting batch_size to 1, the error still happened.

**Comment by Kairobo** [comment]
> ![image](https://private-user-images.githubusercontent.com/35723500/382436991-d9f8dfef-130a-4305-93a1-5f793688862a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MjY4NTMsIm5iZiI6MTczMDUyNjU1MywicGF0aCI6Ii8zNTcyMzUwMC8zODI0MzY5OTEtZDlmOGRmZWYtMTMwYS00MzA1LTkzYTEtNWY3OTM2ODg4NjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDA1NDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlODJmYmM3ZGRlNThkYTYxNTUwY2UwNDA3ZDJkMzczZTk5ZDdhYTJlOTI5OGM1ODVmZDkxZDg1Y2JlNmJmM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bg2vWShHPA5C3MqAGpzQG0NyRESyQNvvj_ZkTBa5EpU)
> 
> Note that I use the get_batch function provided in eval_smpl_long.
> 
> When setting batch_size to 1, the error still happened.

Have you resolved it? Thank you for the catch-up

**Comment by Sirui-Xu** [comment]
I might not be available shortly to fix the issue, but one thing you may try is to use this code [link to code](https://drive.google.com/file/d/1xow6GDCC7tJ8kL7W9E5KmgCJ03jA82Zk/view?usp=sharing), which should be able to work after changing some name of modules.

**Comment by kleinzcy** [comment]
@Kairobo I have not solved the bug. The easy bugs like dimension errors are easy to solve. But the bug related to "jtrs" variable is hard to solve. Denormalize function does not process "jtrs", but the smooth function need to process it. 

I am a newbie to 3D domain.

**Comment by Kairobo** [comment]
Finally, get it can visualize: 
[eval_smpl_long.py.zip](https://github.com/user-attachments/files/17606365/eval_smpl_long.py.zip)
But the evaluation hasn't been done @kleinzcy .

**Comment by kleinzcy** [comment]
@Kairobo Thanks for your code. I also meet the problem of gts. I refer the [code ](https://drive.google.com/file/d/1xow6GDCC7tJ8kL7W9E5KmgCJ03jA82Zk/view?usp=sharing) and modify the dataset test_dataset = Dataset(... future_len=args.future_len ...) to future_len=args.future_len*(args.autoregressive+1). It may include the GT of all predictions. Unfortunately, there are still other bugs.

In addition, the T may be 3. And can you provide the dataset code? (It seems that you implement a light version.)

**Comment by Kairobo** [comment]
Ok. I solved the gt problem (Though, ugly. ). And now, I can run each line. I customized the code a little bit (for example, delete small_data). So, please really carefully to copy each line.
[eval_smpl_long.py.zip](https://github.com/user-attachments/files/17606449/eval_smpl_long.py.zip). One question is should T = 4 for the long sequence? @Sirui-Xu

**Comment by kleinzcy** [comment]
Nice. In my understanding, if we generate 100 future frames, we need to sample four times. And there is a sampling outside T loop, so we have to set T = 3. 

Can you provide the dataset code? I usually meet oserror (OOM) with the current dataset code.

**Comment by Kairobo** [comment]
[dataset_smpl.py.zip](https://github.com/user-attachments/files/17606485/dataset_smpl.py.zip) @kleinzcy 
You're correct. We should have 100 future frames in the paper.

I updated the code to T = 3(there is one before the loop).

[eval_smpl_long.py.zip](https://github.com/user-attachments/files/17606515/eval_smpl_long.py.zip)

**Comment by Sirui-Xu** [comment]
Yes, I use T = 3 (--autoregressive 3) for evaluating 100-frame sequences. To reproduce the paper's results, please set diverse_sample to 10.

I'm glad you resolved the issue! I’ll incorporate this discussion into the upcoming repo update. Thanks for your input!

**Comment by kleinzcy** [comment]
It seems that the evaluation is very slow. Do you have any plan to accelerate the evaluation?

**Comment by Sirui-Xu** [comment]
Apologies for the delay. I’ll prepare an updated version with batched evaluation (the current setup uses a batch size of 1 for long-term evaluation). However, with the CVPR deadline approaching, I won’t have time to complete this before then. I’ll work on it afterward.
