### ISSUE TITLE
Python version conflicts with pytorch3d

### ISSUE THREAD

**Issue by chrenx** [Sirui-Xu/InterDiff#2]
There seem to be a lot of issues when i was setting up the environment. 
The format of "requirements.txt" was not able to be installed by pip. I have to use pip freeze to update the requirements.txt.
One of the required packages "pytorch3d" needs python version >= 3.8 while the readme suggested we use python 3.7. After updating to 3.8, I received error: from pytorch3d import _C. I have tried so many online solutions, but didn't work. 
I wonder if there is any other version of requirements.txt for me to set up the environment.

**Comment by Sirui-Xu** [comment]
Hello,

To accommodate python==3.7 version, you need to downgrade the version of pytorch3d, e.g. pytorch3d==0.7.0.

Please also check a detailed environment requirement I just uploaded for python==3.8 at https://github.com/Sirui-Xu/InterDiff/blob/main/environment.yml.

Thanks!
