### ISSUE TITLE
human-body-prior==2.2.2.0

### ISSUE THREAD

**Issue by chrenx** [Sirui-Xu/InterDiff#3]
The latest human-body-prior I found in pip was 0.8.5.0, while in the environment.yml it suggests human-body-prior==2.2.2.0. Which version are we supposed to use?

Thanks,
C

**Comment by Sirui-Xu** [comment]
Hi, 

for some of the packages, you may need to install them from the source (https://github.com/nghorbani/human_body_prior#installation)

Best
