### ISSUE TITLE
Unable to load pointnet2_ops

### ISSUE THREAD

**Issue by chrenx** [Sirui-Xu/InterDiff#7]
Hello,

I got this warning "UserWarning: Unable to load pointnet2_ops cpp extension. JIT Compiling."
One solution was downgrading torchvision to version 0.5.0 which also changes torch to lower version 1.4. Unfortunately, this version seems incompatible with pytorch-lightning. I wonder if there is any way to solve this conflict dependency?

**Comment by Sirui-Xu** [comment]
Hi,

I don't have this warning on my own Python 3.7 environment, maybe this is caused by the 3.8 environment, I'll have to check with my collaborators. Also, does this warning affect the actual running of the program?

Best

**Comment by chrenx** [comment]
somehow it was fixed, although I don't quite know why. lol. Thanks!
